# Generated by Django 4.0.6 on 2023-03-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_location_center_lat_alter_location_center_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='center_lat',
            new_name='centre_lat',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='center_long',
            new_name='centre_long',
        ),
    ]
