# Generated by Django 4.0.6 on 2023-04-08 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_issue_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schedule'),
        ),
    ]
