# Generated by Django 4.0.6 on 2023-04-08 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_rename_course_enrollment_course_id_and_more'),
        ('api', '0005_alter_issue_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='schedule',
            new_name='schedule_id',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='schedule',
            new_name='schedule_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='subject',
            new_name='subject_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecturer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.lecturer'),
        ),
    ]
