# Generated by Django 4.0.6 on 2023-04-08 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_rename_course_enrollment_course_id_and_more'),
        ('api', '0006_rename_schedule_attendance_schedule_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lecturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.lecturer'),
        ),
    ]
