# Generated by Django 4.0.6 on 2023-04-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_schedule_lecturer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='lecturer_id',
            new_name='lecturer',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
