# Generated by Django 4.0.6 on 2023-04-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_schedule_id_attendance_schedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='student_id',
            new_name='student',
        ),
    ]
