# Generated by Django 4.0.6 on 2023-04-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_schedule_id_issue_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
