# Generated by Django 4.0.6 on 2023-04-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_schedule_day_of_week_alter_schedule_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(max_length=255),
        ),
    ]
