# Generated by Django 4.0.6 on 2023-05-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_schedule_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='centre_lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='centre_long',
        ),
        migrations.RemoveField(
            model_name='location',
            name='radius',
        ),
        migrations.AddField(
            model_name='location',
            name='polygon_points',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
