# Generated by Django 4.0.6 on 2023-05-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_location_centre_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='method_used',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
