# Generated by Django 4.0.6 on 2023-05-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_attendance_method_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='method_used',
        ),
    ]
