# Generated by Django 4.0.6 on 2023-05-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_attendance_method_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
    ]
