# Generated by Django 4.0.6 on 2023-05-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_attendance_is_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='auth_method',
            field=models.CharField(choices=[('local_auth', 'local_auth'), ('face_recognition_service', 'face_recognition_service'), ('other', 'other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_signed_in',
            field=models.DateTimeField(),
        ),
    ]
