# Generated by Django 4.0.6 on 2023-06-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_attendance_auth_method_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
