# Generated by Django 4.0.6 on 2023-03-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image_path',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
    ]
