# Generated by Django 4.0.6 on 2023-03-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.lecturer'),
        ),
    ]
