# Generated by Django 4.0.6 on 2023-03-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_enrollment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
