# Generated by Django 4.0.6 on 2023-04-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_lecturer_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='lecturer',
            new_name='lecturer_id',
        ),
    ]
