# Generated by Django 4.0.6 on 2023-04-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_rename_course_enrollment_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='lecturer_id',
            new_name='lecturer',
        ),
    ]
