# Generated by Django 4.0.6 on 2023-04-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_rename_course_id_subject_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student_id',
            new_name='student',
        ),
    ]
