# Generated by Django 4.0.6 on 2023-05-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_image_encodings',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
